export type Issue = {
  id: string;
  createdAt: string;
  updatedAt: string;
  archivedAt: null | string;
  number: number;
  title: string;
  priority: number;
  estimate?: null | string;
  boardOrder?: number;
  sortOrder?: number;
  startedAt?: null | string;
  completedAt?: null | string;
  canceledAt?: null | string;
  autoClosedAt?: null | string;
  autoArchivedAt?: null | string;
  dueDate?: null | string;
  trashed?: null | string;
  snoozedUntilAt?: null | string;
  labelIds: string[];
  teamId: string;
  cycleId?: null | string;
  projectId?: null | string;
  subscriberIds?: string[];
  previousIdentifiers?: string[];
  creatorId: string;
  assigneeId: string;
  snoozedById?: null | string;
  issueImportId?: null | string;
  stateId?: string;
  parentId?: null | string;
  subIssueSortOrder?: null | string;
  sourceMetadata?: null | string;
  descriptionData?: null | string;
  documentVersion?: number;
};

export type Organization = {
  id: string;
  createdAt: string;
  updatedAt: string;
  archivedAt?: null | string;
  name: string;
  urlKey: string;
  logoUrl?: string;
  periodUploadVolume?: number;
  gitBranchFormat?: null | string;
  gitLinkbackMessagesEnabled?: boolean;
  gitPublicLinkbackMessagesEnabled?: boolean;
  roadmapEnabled?: boolean;
  samlEnabled?: boolean;
  allowedAuthServices?: unknown[];
  deletionRequestedAt?: null | string;
  reducedPersonalInformation?: boolean;
  enabled: boolean;
  deletionRequestedById?: null | string;
  serviceId?: string;
  linearPreviewFlags?: {
    [k: string]: unknown;
  };
};
